#pragma once
#include "node_graph.h"
#include "transport.h"
#include "granular_freeze.h"   // GrainFreezeVoice - shared freeze-mode reader
#include "warp.h"              // WarpOp / WarpMethod - frame-scope shape bending
#include "wavetable_frame.h"   // IWavetableFrame - cached frame for live re-bake
#include <juce_audio_processors/juce_audio_processors.h>
#include <vector>
#include <string>
#include <cmath>
#include <functional>
#include <array>
#include <cstdint>

namespace SoundShop {

// Script-runtime language selector (Builtin / Lua / Wasm), defined in
// script_runtime.h. Forward-declared here so Terrain::fillFromScript can take
// it without the header pulling in the whole runtime stack.
enum class ScriptLang;

// ============================================================================
// Video terrain script (#video-import)
// ----------------------------------------------------------------------------
// A Terrain Synth node imported from video stores everything in node.script as:
//   __video__:<path>|<t0>,<t1>|<cx>,<cy>,<cw>,<ch>|<outW>,<outH>,<outFrames>|<base64 gray>
// The trailing base64 blob is the downscaled grayscale grid (frame-major,
// row-major, 8-bit) - so reloading needs neither ffmpeg nor the original video
// file. The source path + time/crop/scale params are retained so the import
// dialog can be reopened to re-crop (which DOES need the video file + ffmpeg).
// `|` is illegal in Windows paths and absent from the base64 alphabet, so it's
// a safe field separator; the path is reassembled from all leading fields so a
// stray `|` in a POSIX path can't break parsing.
// ============================================================================
struct VideoTerrainParams {
    std::string path;
    double t0 = 0.0, t1 = 0.0;          // time crop (seconds)
    int cropX = 0, cropY = 0, cropW = 0, cropH = 0;   // source-pixel XY crop
    int outW = 0, outH = 0, outFrames = 0;            // downscaled grid size
    std::vector<uint8_t> gray;          // outW*outH*outFrames, frame-major
};

// Encode params (incl. the gray grid) into a __video__: node script.
std::string makeVideoTerrainScript(const VideoTerrainParams& p);
// Decode a __video__: script. When wantGray is false the (large) base64 blob
// is skipped - useful when the dialog only needs the crop/scale params to
// re-seed its controls. Returns false if the script isn't a video script.
bool parseVideoTerrainScript(const std::string& script, VideoTerrainParams& out,
                             bool wantGray = true);

// ============================================================================
// Programmatic terrain source (#generate)
// ----------------------------------------------------------------------------
// A Terrain Synth node generated by a user program stores everything needed to
// rebuild it in node.script as:
//   __generate__:<langInt>[:<modeInt>]|<dim0>,...,<dimN-1>|<b64 src>|<b64 data>
// where <langInt> is a GenLang value, the optional :<modeInt> is the generation
// mode (0 per-cell / 1 whole-grid; absent => per-cell, for old projects), the
// comma list is the grid shape (any rank), <b64 src> is the program source
// base64-encoded (so it can contain newlines / `|`), and <b64 data> is the BAKED
// terrain grid: the final bipolar float cells, gzip-compressed then base64'd.
//
// The data is baked rather than recomputed on load. Generation runs once on the
// message thread (Generate / Edit Source) and the result travels in the tag, so
// loading a project just deserialises - no interpreter runs during graph rebuild
// (which happens on the AUDIO thread, where embedded Python is illegal and a
// heavy per-cell loop would glitch audio). The source is retained so the dialog
// can reopen and regenerate. If the data field is empty (legacy tag / hand-edit)
// the node falls back to recomputing from source for Builtin/Lua.
// ============================================================================

// Generation languages offered by the Generate dialog. Builtin/Lua map to
// ScriptLang (so they can use the IScriptRuntime path), but Python is NOT a
// ScriptLang (it can't run in the audio-thread per-sample/per-block runtimes) -
// it generates via the embedded-CPython ScriptEngine and ALWAYS bakes.
//
// CRITICAL: GenLang and ScriptLang share integer values for Builtin (0) and Lua
// (1) ONLY. They DIVERGE past that: GenLang::Python == 2 but ScriptLang::Wasm ==
// 2, and GenLang::Wasm == 4 (not 2). So NEVER blind-cast (ScriptLang)(int)gen -
// it silently turns Python into Wasm. The Builtin/Lua/Wasm GenLangs that ARE
// backed by a ScriptLang runtime must be mapped explicitly (see
// generate_dialog.cpp genLangToScriptLang); Python/Glsl have their own bake paths
// and must never be cast to a ScriptLang at all.
//
// Glsl (3) is like Python in that it can't run on the audio thread and ALWAYS
// bakes: it dispatches a GLSL compute shader on an offscreen GL 4.3 context
// (Terrain::fillFromGlsl / glsl_compute.h). It is NOT a ScriptLang.
//
// Wasm (4) runs a PRE-COMPILED .wasm module (chosen as a file, not typed source)
// through the same WasmRuntime the Script (WASM) audio node uses, but via the
// whole-grid runGenerate() path: the module exports ss_generate() and fills the
// grid through ss_grid_* host imports (see script_runtime_wasm.cpp /
// soundshop_wasm.h). WASM is block-only, so it offers WHOLE-GRID generation only
// (no per-cell mode). The baked grid is stored like every other language.
enum class GenLang { Builtin = 0, Lua = 1, Python = 2, Glsl = 3, Wasm = 4 };

struct GenerateTerrainParams {
    int lang = 0;                  // generation language (GenLang: Builtin=0, Lua=1, Python=2, Glsl=3)
    int mode = 0;                  // 0 = per-cell (one call per cell), 1 = whole-grid
    int passes = 1;                // GLSL whole-grid ping-pong iteration count (1 = single
                                   // pass). Only meaningful for lang==Glsl && mode==1; the
                                   // shader runs `passes` times, each reading the previous
                                   // pass's output (prev[]) and writing data[] — enabling
                                   // convolution/blur, cellular automata, diffusion, etc.
                                   // Ignored by other languages/modes.
    std::vector<int> dims;         // grid shape, any rank
    std::string source;            // generator program source (raw)
    // Baked terrain data (the FINAL bipolar [-1,1] cells, length = product(dims)).
    // Generation runs ONCE - when the user clicks Generate / Edit Source on the
    // message thread - and the computed grid is baked here, then stored in the
    // node tag (gzip+base64). On load the node deserialises this directly and
    // never re-runs the generator, so (a) Python (which can't run on the audio
    // thread where the processor is constructed) works like any other language,
    // and (b) no language pays interpreter cost on graph rebuild. Empty = no bake
    // yet (legacy tags / hand-edits); Builtin/Lua then regenerate as a fallback.
    std::vector<float> data;
};

// Encode params into a __generate__: node script (source is base64-encoded).
//
// The baked grid is NOT embedded in the script. When `store` is non-null and
// `p.data` is present, the grid is put into the content store and the script's
// 4th field carries only the short content hash (prefixed '#'). The bytes then
// live once in the store (out of undo snapshots, deduped) - see content_store.h.
// When `store` is null (e.g. unit tests with no graph), the grid is embedded
// inline as legacy gzip+base64 so make/parse still round-trip standalone.
std::string makeGenerateTerrainScript(const GenerateTerrainParams& p,
                                      ContentStore* store = nullptr);
// Decode a __generate__: script. Returns false if the script isn't a generate
// script or is malformed. A '#'-prefixed 4th field is a content hash, resolved
// against `store` (null store -> data left empty, loader regenerates/falls back);
// a bare base64 4th field is a legacy inline blob, decoded directly.
bool parseGenerateTerrainScript(const std::string& script, GenerateTerrainParams& out,
                                ContentStore* store = nullptr);
// Lightweight rank probe: returns the dimension count of a __generate__ script,
// parsed from its dims field with no blob resolution (cheap - safe to call when
// building a context menu). Returns 0 if `script` isn't a generate script.
int generateScriptRank(const std::string& script);

// ==============================================================================
// N-dimensional terrain of audio data
// ==============================================================================

class Terrain {
public:
    // Dimensions and sizes (e.g., {512, 512} for a 2D 512x512 terrain)
    void init(const std::vector<int>& dimensions);
    int numDimensions() const { return (int)dims.size(); }
    const std::vector<int>& getDimensions() const { return dims; }
    int totalSize() const { return (int)data.size(); }

    // Access: coordinate is a vector of floats in [0,1] per dimension
    // Interpolates between neighboring samples (N-linear interpolation)
    float sample(const std::vector<float>& coord) const;

    // Raw access by flat index
    float& at(int flatIndex) { return data[flatIndex]; }
    float at(int flatIndex) const { return data[flatIndex]; }

    // Fill methods
    void fillFromExpression(const std::string& expr);   // vars: x, y, z, w...

    // Generate terrain by running a user SCRIPT once per cell, in any of the
    // script-runtime languages that support per-cell (PerSample) execution
    // (Builtin, Lua). Unlike fillFromExpression's 8-letter axis cap, this binds
    // the coordinate as an UNBOUNDED indexed array so terrains of any rank work:
    // for each cell the runtime sees globals c0..c{nd-1} = normalized coordinate
    // in [0,1], the first four also aliased to x,y,z,w in [0,2*pi] (matching
    // fillFromExpression so Builtin axis math behaves the same), and nd = the
    // number of dimensions.
    //
    // OUTPUT CONTRACT: the script returns a value in [0,1] - think of it as a
    // grayscale heightmap / image brightness - which is mapped to the terrain's
    // bipolar [-1,1] as v*2-1, exactly like fillFromImage / fillFromVideoData.
    // (This 0..1 contract, rather than fillFromExpression's bipolar -1..1 one,
    // is dictated by the script runtime: the Signal role clamps Lua output to
    // [0,1] - the unipolar control-signal convention - so a bipolar-native
    // contract couldn't be honoured uniformly across languages. Builtin output
    // is clamped to [0,1] here too so both languages behave identically.)
    //
    // `dimensions` sets the grid shape. Returns false and fills `error` if the
    // language backend is unavailable, the program fails to load, or the
    // language is block-only (e.g. Wasm) and so can't run per-cell. Generation
    // is one-time (offline), so per-cell interpreter cost is acceptable.
    bool fillFromScript(ScriptLang lang, const std::string& src,
                        const std::vector<int>& dimensions, std::string& error);

    // Whole-grid ("whole-grid mode") variant: the program runs ONCE and owns the
    // entire array, rather than being called per cell. This unlocks cross-cell
    // algorithms a per-cell program physically cannot express - convolution /
    // blur, cellular automata, FFT, iterative relaxation, global normalisation -
    // because every cell can read every other cell. The runtime exposes the grid
    // shape (Lua globals `dims`, `nd`, `total`) plus get/set(i,v) and coord(i,ax)
    // helpers and runs the program's `generate()` entry (see runGenerate()).
    // Same OUTPUT CONTRACT as fillFromScript: each cell is set in [0,1] and
    // mapped to bipolar [-1,1] as v*2-1. Returns false and fills `error` if the
    // language can't generate a whole grid (only languages that support PerBlock
    // - currently Lua) or the program fails. `dimensions` sets the grid shape.
    bool fillFromScriptWholeGrid(ScriptLang lang, const std::string& src,
                                 const std::vector<int>& dimensions,
                                 std::string& error);

    // GLSL compute-shader generation (offline GPU bake; see glsl_compute.h).
    // SEANCE has no live GL context, so this stands up an offscreen GL 4.3 core
    // context on demand and dispatches a compute shader that writes the grid.
    // `userBody` is templated into a generated shader:
    //  - per-cell (wholeGrid=false): the body of a function that returns a float
    //    in [0,1] given the SAME coordinate vocabulary as fillFromScript -
    //    c[d] (normalized [0,1]), x,y,z,w (= c0..c3 * 2*pi), nd, plus int
    //    coord[d] (cell index) and dims[d] (extent). GLSL fixed-array cap = 16D.
    //  - whole-grid (wholeGrid=true): the body of main() with direct access to
    //    data[] (the output SSBO at binding 0), gl_GlobalInvocationID, uTotal,
    //    nd, uDims[], and a coordOf(idx,axis) helper. The program writes
    //    data[gid] itself.
    //
    // `passes` (whole-grid only; ignored for per-cell) drives multi-pass
    // "ping-pong" iteration: when > 1, the shader runs `passes` times over two
    // alternating buffers. Each pass reads the PREVIOUS pass's full output via a
    // read-only prev[] buffer (binding 1) and writes data[] (binding 0); the two
    // swap after every pass. This is what makes cross-cell work — convolution/
    // blur, cellular automata, diffusion/erosion — correct, since neighbour reads
    // see a stable snapshot rather than a half-updated buffer. The whole-grid
    // template additionally exposes uPass (current pass index), uNumPasses,
    // prev[]/prevAt(idx), and neighbour helpers (coordAxis, neighbor). On pass 0
    // prev[] is all zeros, so a typical program seeds on uPass==0 and iterates
    // thereafter. passes==1 is exactly the old single-pass behaviour.
    //
    // OUTPUT CONTRACT matches fillFromScript: values in [0,1] are mapped to the
    // terrain's bipolar [-1,1] as v*2-1, clamped on readback (NaN -> 0). Returns
    // false + fills `error` if GL is unavailable or the shader fails to
    // compile/link/run. BAKE-TIME ONLY - never call on the audio thread (no GL
    // context there); the audio-path fallback treats GLSL like Python (flat
    // grid until a bake exists).
    bool fillFromGlsl(const std::string& userBody, bool wholeGrid,
                      const std::vector<int>& dimensions, std::string& error,
                      int passes = 1);

    void fillFromImage(const std::string& path);         // 2D, pixel brightness
    void fillFromAudioFile(const std::string& path);     // 1D, raw samples

    // Build a 3D terrain {frames, h, w} from a decoded video grid: `gray` is
    // frame-major, row-major brightness bytes (0..255) of size frames*h*w.
    // Each cell becomes b/255*2-1, mirroring fillFromImage's mapping. The data
    // is baked into the node script (see makeVideoTerrainScript), so this is
    // what runs on project load - no video file or ffmpeg needed.
    void fillFromVideoData(const std::vector<uint8_t>& gray,
                           int frames, int h, int w);

    // Fractal / self-similar fill (#51): build a 1D waveform from recursive
    // wavelet coefficient patterns. The base pattern is a short seed
    // waveform; at each DWT level, the detail coefficients are scaled
    // copies of the seed. The 1/f-ish spectrum produces rich, organic
    // waveforms. `iterations` = number of self-similar recursion levels.
    void fillFractal(int size, int iterations = 5, float decay = 0.7f);

    // Wavelet-basis storage (#49): convert terrain data to/from DWT
    // coefficient representation. When stored as coefficients,
    // interpolation between frames happens in the wavelet domain
    // (smoother than time-domain averaging), and reconstruction is
    // a single IDWT per block. Call toWaveletBasis() after filling
    // the terrain to convert; fromWaveletBasis() to reconstruct.
    void toWaveletBasis(int levels = 4);
    void fromWaveletBasis(int levels = 4);
    bool isWaveletBasis = false;

    // Wavetable mipmap pyramid (#48): for anti-aliased pitch-up.
    // Each level is a half-resolution version of the previous, created
    // by DWT -> drop finest detail -> IDWT. Higher-pitched playback uses
    // smaller mipmaps to avoid aliasing. Call buildMipmaps() after
    // filling the terrain with a 1D wavetable. The playback code picks
    // the level based on the current pitch ratio.
    std::vector<std::vector<float>> mipmaps; // [0] = original, [1] = half, etc.
    void buildMipmaps(int maxLevels = 6);
    // Sample from the appropriate mipmap level for a given pitch ratio.
    // pitchRatio = playback_freq / base_freq. Higher ratio -> smaller mipmap.
    float sampleMipmap(float phase01, float pitchRatio) const;

    // Frequency-domain fill (1D only). Evaluates magExpr(f) and phaseExpr(f)
    // over FFT bins, inverse-FFTs to a real waveform, and fills this terrain
    // (which should be 1D of size == fftSize). Normalized to peak 1.0.
    // phaseMode: 0=expression 1=random 2=zero 3=linear
    void fillFromSpectralExpression(const std::string& magExpr,
                                    const std::string& phaseExpr,
                                    int fftSize,
                                    int phaseMode);

    // Frequency-domain fill from a SpectralDoc: each curve (mag, phase) is
    // evaluated as either an expression or a drawn curve, then combined
    // into a complex spectrum and inverse-FFTed. The doc carries its own
    // fftSize. Normalized to peak 1.0.
    void fillFromSpectralDoc(const struct SpectralDoc& doc);
    void fillConstant(float value);
    void fillNoise(unsigned int seed = 42);

    // Fractal value noise (N-D). Generates `octaves` coarse random grids of
    // doubling resolution, smoothstep-interpolates each into the terrain, and
    // sums with amplitude * persistence^octave. The result is a smooth,
    // 1/f-like bumpy field - the orbit reads it as varying noisy texture
    // instead of independent samples (which would just degenerate into a
    // noise oscillator). Persistence in (0,1): lower = smoother / fewer
    // high-frequency details; higher = harsher / more detail. Result is
    // peak-normalized to 1.0.
    void fillValueNoise(int octaves = 4, float persistence = 0.55f, unsigned int seed = 42);

    void smooth(int passes = 2);            // Gaussian blur to reduce quantization noise

    // Get raw data for display
    const std::vector<float>& getData() const { return data; }
    std::vector<float>& getData() { return data; }

    int coordToFlatIndex(const std::vector<int>& indices) const;

private:
    std::vector<int> dims;      // size of each dimension
    std::vector<float> data;    // flat array, row-major order
};

// ==============================================================================
// Traversal: maps time -> N-dimensional coordinate
// ==============================================================================

enum class TraversalMode {
    Linear,       // sweep along one axis
    Orbit,        // circle/ellipse on 2D plane (generalizes to N-D)
    Lissajous,    // sine-driven per axis with different frequencies
    Path,         // user-defined sequence of control points
    Physics,      // gravity wells, bouncing point
    Custom,       // expression or code-defined
    Static        // no automatic motion - held at Center per axis (drive Center
                  // manually or with a signal cable). Lets the user turn the
                  // circling oscillators off entirely.
};

struct TraversalParams {
    TraversalMode mode = TraversalMode::Orbit;

    // Orbit params
    float centerX = 0.5f, centerY = 0.5f;  // center position [0,1]
    float radiusX = 0.3f, radiusY = 0.3f;  // ellipse radii
    float speed = 1.0f;                      // cycles per beat
    float radiusModSpeed = 0.0f;             // radius change over time
    float radiusModAmount = 0.0f;

    // Lissajous params (per dimension, up to 8)
    struct AxisParams {
        float frequency = 1.0f;   // relative frequency
        float phase = 0.0f;       // initial phase offset [0,1]
        float center = 0.5f;      // center position [0,1]
        float amplitude = 0.4f;   // swing [0,0.5]
    };
    std::array<AxisParams, 8> axes;

    // Linear params
    int linearAxis = 0;            // which dimension to sweep
    float linearSpeed = 1.0f;      // sweeps per beat

    // Physics params
    float friction = 0.01f;
    float gravity = 0.5f;
    struct Attractor { float x, y, strength; };
    std::vector<Attractor> attractors;

    // Path params
    struct PathPoint { float time; std::vector<float> coord; }; // time in beats
    std::vector<PathPoint> pathPoints;

    // Custom expression: returns coord per axis
    // Variables: t (time in beats), bpm, sr
    std::string customExpr;
};

class Traversal {
public:
    // Evaluate position at a given time (in beats)
    std::vector<float> evaluate(const TraversalParams& params, int numDims,
                                 double beatTime, double bpm, double sampleRate) const;

private:
    // Physics state (mutable for simulation stepping)
    mutable std::vector<float> physPos;
    mutable std::vector<float> physVel;
    mutable double lastPhysBeat = -1;
};

// ==============================================================================
// Terrain Synth mode
// ==============================================================================

// Three render modes for terrain synth:
//   Direct (SamplePerPoint) - read the terrain value as the audio sample.
//     Classic wavetable / sample playback. Natural for 1D wavetables and
//     1D audio files where the terrain "is" a waveform.
//   AmSine (WaveformPerPoint) - run a sine oscillator at the played pitch,
//     and use the terrain value at each sample to amplitude-modulate it.
//     Generic terrain sonification: the only mode that produces meaningful
//     sound for non-1D terrains (2D images, math expressions, fractal
//     noise) where Direct mode would just be noise.
//   AdditiveBank - FFT the 1D wavetable cycle to extract harmonic
//     magnitudes/phases, then synthesize per-note as a sum of independent
//     sine partials running at fundamental x ratio. Applies only to terrains
//     that are 1D wavetable cycles. Unlike Direct mode (where you hear the
//     baked cycle through one oscillator) each partial is a live sine, so
//     inharmonic stretches are aliased-free and per-partial modulation
//     becomes possible.
enum class TerrainSynthMode {
    SamplePerPoint,    // Direct: terrain value IS the audio sample
    WaveformPerPoint,  // AM-sine: terrain value AM-modulates a pitched sine
    AdditiveBank       // Additive: FFT the cycle, run a partial bank
};

// How many partials the additive-bank mode synthesises. Higher = brighter
// and more accurate to the wavetable, more CPU. 32 is a reasonable default
// (covers up to ~3.5kHz of harmonics for a low A note at 110Hz).
inline constexpr int kAdditiveBankMaxPartials = 64;

// Classification of what kind of source feeds a TerrainSynthProcessor.
// Different sources make different synthesis modes meaningful:
//   Wavetable - a single 1D cycle (or an N-D wavetable where the Position
//     knob picks a 1D slice every block). Direct (play the cycle) and
//     AdditiveBank (FFT the cycle, sum its partials) both apply. AM-sine
//     is degenerate here: a sine carrier at the played pitch, AM-modulated
//     by the cycle moving at the SAME played pitch, just distorts the
//     cycle into something less musical than the direct cycle itself.
//   Sample - a 1D audio recording (the Sampler / MultiSampler case). Only
//     Direct (sample playback at the transposed rate) makes musical sense.
//     The recording IS the sound, not a single cycle, so the FFT-cycle
//     assumption Additive bank makes doesn't hold; AM-sine reshapes the
//     recording into something rarely useful.
//   Surface - an N-D sonification source (2D image, math expr with y/z/w,
//     2D+ fractal noise). Direct mode reads raw pixel/voxel values into
//     the audio stream, producing noise. AM-sine is the only musical
//     mode here - the terrain becomes a slow amplitude envelope on a
//     pitched sine carrier.
enum class SynthSourceClass {
    Wavetable,
    Sample,
    Surface
};

struct SynthModeAvailability {
    bool direct       = false;
    bool amSine       = false;
    bool additiveBank = false;
    bool allows(TerrainSynthMode m) const {
        switch (m) {
            case TerrainSynthMode::SamplePerPoint:   return direct;
            case TerrainSynthMode::WaveformPerPoint: return amSine;
            case TerrainSynthMode::AdditiveBank:     return additiveBank;
        }
        return false;
    }
    // Snap a candidate mode to the nearest applicable one. Preference order
    // is the mode itself if allowed, then Direct, then AM-sine, then
    // AdditiveBank, so a project with a stale invalid mode always falls
    // back to a sensible default.
    TerrainSynthMode clamp(TerrainSynthMode m) const {
        if (allows(m)) return m;
        if (direct)       return TerrainSynthMode::SamplePerPoint;
        if (amSine)       return TerrainSynthMode::WaveformPerPoint;
        if (additiveBank) return TerrainSynthMode::AdditiveBank;
        return m;
    }
};

// ---- Standalone single-frame synth ("__framesynth__:") ----------------------
//
// A standalone single-frame instrument node (Layered / Frequency Domain /
// Wavelet Space / Inharmonic / Sample / Granular) stores its script as
//   "__framesynth__:" + <a complete single-frame WavetableDoc encode>
// i.e. the body after the prefix is a normal "__wavetable5__:..." string with
// exactly one library entry placed in a 1x1 grid. The prefix exists only to
// route the node to its focused single-frame editor (no grid / library / multi-
// frame morph UI); for *rendering* the synth simply strips the prefix and runs
// the existing wavetable path verbatim - so every per-frame-type voice
// (granular OLA, inharmonic additive, cycle terrain) is shared with zero
// duplication. effectiveSynthScript() does that strip; isFrameSynthScript()
// tests for the prefix.
inline constexpr const char* kFrameSynthPrefix = "__framesynth__:";

inline bool isFrameSynthScript(const std::string& script) {
    return script.rfind(kFrameSynthPrefix, 0) == 0;
}

// Return the script the synth should actually render: for a "__framesynth__:"
// node, the wrapped wavetable body; otherwise the script unchanged.
inline std::string effectiveSynthScript(const std::string& script) {
    if (isFrameSynthScript(script))
        return script.substr(std::char_traits<char>::length(kFrameSynthPrefix));
    return script;
}

// Classify a TerrainSynthProcessor source by its script prefix. Mirrors
// the source-detection chain in TerrainSynthProcessor::reloadIfScriptChanged,
// kept as a free function so the node-graph UI can filter the Synth Mode
// picker without holding a pointer to the audio processor.
// "__framesynth__:" wrappers are classified by their wrapped body.
SynthSourceClass     classifySynthSource(const std::string& script);
SynthModeAvailability synthModeAvailabilityFor(SynthSourceClass cls);

// ==============================================================================
// Terrain Synth Processor
// ==============================================================================

class TerrainSynthProcessor : public juce::AudioProcessor {
public:
    // `store` resolves '#'-hash baked-grid references in __generate__ scripts
    // against the graph's content store. Null is tolerated (grid left empty ->
    // Builtin/Lua regenerate, Python falls back to a flat grid).
    TerrainSynthProcessor(Node& node, Transport& transport, ContentStore* store = nullptr);

    const juce::String getName() const override { return node.name; }
    void prepareToPlay(double sr, int bs) override;
    void releaseResources() override {}
    void processBlock(juce::AudioBuffer<float>& buf, juce::MidiBuffer& midi) override;
    // Tail = ADSR release (param idx 3).  No magic constant - reads the
    // live param value so changing release shrinks/extends the tail.
    double getTailLengthSeconds() const override { return (double) getParam(3, 0.3f); }
    // Transport panic (Stop): hard-reset every voice's amp envelope so release
    // tails are cut immediately instead of fading out over the release time.
    void reset() override {
        for (auto& v : voices) v.env.hardReset();
    }
    bool acceptsMidi() const override { return true; }
    bool producesMidi() const override { return false; }
    bool isBusesLayoutSupported(const BusesLayout&) const override { return true; }
    juce::AudioProcessorEditor* createEditor() override { return nullptr; }
    bool hasEditor() const override { return false; }
    int getNumPrograms() override { return 1; }
    int getCurrentProgram() override { return 0; }
    void setCurrentProgram(int) override {}
    const juce::String getProgramName(int) override { return {}; }
    void changeProgramName(int, const juce::String&) override {}
    void getStateInformation(juce::MemoryBlock&) override {}
    void setStateInformation(const void*, int) override {}

    // Access for UI
    Terrain& getTerrain() { return terrain; }
    TraversalParams& getTraversalParams() { return traversalParams; }
    TerrainSynthMode getMode() const { return mode; }
    void setMode(TerrainSynthMode m) { mode = m; }

    // Get the current traversal position (for visualization)
    std::vector<float> getCurrentPosition() const { return lastPosition; }

    // Check if node.script changed since last processBlock and re-parse
    // the terrain data if so. This lets the layered editor commit changes
    // to node.script without triggering a full graph rebuild (#23).
    void reloadIfScriptChanged();

private:
    Node& node;
    Transport& transport;
    double sampleRate = 44100;

    // Cached copy of node.script from the last parse. When processBlock
    // detects that node.script differs, it triggers a re-parse.
    std::string cachedScript;

    // Sustained editor-audition tracking (node.heldAudition). LEVEL-triggered:
    // each block we reconcile this processor's held voice against the node's
    // heldAudition state so the audition survives graph rebuilds (a fresh
    // processor re-establishes the voice). heldAuditionActive is per-processor
    // and defaults to false, so a rebuilt processor re-starts the held note;
    // heldAuditionPitch remembers which note to release when it clears.
    bool heldAuditionActive = false;
    int  heldAuditionPitch  = -1;

    Terrain terrain;
    Traversal traversal;
    TraversalParams traversalParams;
    TerrainSynthMode mode = TerrainSynthMode::SamplePerPoint;

    // Wavetable-synth mode: when true, terrain is a 2D buffer of stacked
    // frames {tableSize, nFrames}. coord[1] is the frame position and is
    // driven by the "Position" node param (index 21) rather than traversal.
    bool isWavetable = false;
    // Audio-sample playback: when true, the terrain holds a 1D audio
    // recording (loaded from __audio__:path). Used to classify the source
    // for SynthSourceClass::Sample so the Synth Mode picker only offers
    // Direct (sample playback) rather than AM-sine / AdditiveBank, which
    // don't make musical sense on a recording.
    bool isAudioSample = false;
    int  wtFrameCount = 0;
    int  wtNumDims = 0; // number of *geometric* Position dimensions (1D, 2D, ...)
    // Geometric axis index for each exposed Position param, in param order.
    // Grid exposes a Position param only for *traversable* axes (grid size>=2),
    // numbered contiguously, so the k-th param drives geometric axis
    // wtEffectiveAxes[k]; inert (single-cell) axes have no param and are pinned
    // to coord 0. Mirror of WavetableDoc::effectiveAxes(). For scatter this is
    // all dims (when traversable) or empty (single frame, normalized blend).
    std::vector<int> wtEffectiveAxes;

    // ---- Per-frame live morph re-bake (per-frame morph chains + #88) ----
    //
    // Each layered frame in the wavetable owns its OWN summation-morph chain
    // (IWavetableFrame::morphChain) plus per-layer warp ops. At rebuild we bake
    // every frame's RESTING morph into the terrain/scatter table via
    // renderMorphed(). For frames whose morph amounts or per-layer warp ops are
    // wired to live node params, we ALSO keep a RebakeFrame entry so processBlock
    // can re-render that one frame's cycle each block with the live amounts and
    // write it back into its slot - BEFORE the cross-frame blend, so each frame
    // shapes independently and morphs blend the shaped cycles.
    //
    // This replaces the old doc-level frame-scope warp (one chain shared by ALL
    // frames, applied per sample AFTER the blend) and the single-frame-only
    // wtLayeredFrame re-bake. Per-frame morph genuinely requires per-frame bake.
    struct RebakeFrame {
        std::unique_ptr<IWavetableFrame> frame; // clone (typeId "layered"), tableSize set
        int frameId   = -1;   // library id - param lookup key (Param::warpFrameId)
        int tableSize = 0;
        // Destination. scatterIndex >= 0 -> wtScatterFrameSamples[scatterIndex];
        // otherwise grid: terrain.data[i * gridStride + gridOffset], i in [0,ts).
        int scatterIndex = -1;
        int gridOffset   = 0;
        int gridStride   = 0;
        // This frame's morph chain (resting amounts); live amounts come from
        // (warpFrameId, warpLayer == -1, warpSlot) params each block.
        std::vector<WarpOp> morphChain;
        // Change-detection caches so an unmodulated frame skips the re-render
        // after the first priming block. NaN-aware compare (see rebakeFramesIfNeeded).
        std::vector<std::vector<float>> lastLayerOverrides;
        std::vector<float> lastPhaseOv, lastAmpOv, lastShapeOv, lastShape2Ov;
        std::vector<float> lastMorphAmounts;
    };
    std::vector<RebakeFrame> wtRebakeFrames;

    // Re-render each modulated frame's cycle with live morph/per-layer amounts
    // and write it back into its terrain/scatter slot. Called once per block,
    // before the cross-frame blend. No-op when wtRebakeFrames is empty.
    void rebakeFramesIfNeeded(const Node& node);

    // Scatter wavetable: instead of a rectilinear terrain, frames are stored
    // explicitly with their N-D positions. Each block we compute a Wendland
    // RBF blend at the current Position into a 1D terrain so the per-sample
    // path stays unchanged.
    bool wtScatter = false;
    int  wtScatterDims = 0;
    float wtScatterRadius = 0.45f;
    // Mirror of WavetableDoc::absoluteBlend. When true the blend uses raw
    // weights as gain ("fades volume") instead of normalizing:
    //   - Scatter: raw Wendland weights as gain (distance fades volume).
    //   - Grid: no occupancy renormalization (empty cells fade volume).
    // When false (default) the blend is volume-normalized in both modes.
    bool wtAbsoluteBlend = false;

    // Grid-only occupancy mask, parallel to `terrain` but over the *morph*
    // axes alone (gridDims, no phase axis): 1.0 where a cell holds a frame
    // (cycle or granular), 0.0 where the cell is empty. Sampled at the morph
    // coordinate to get the fraction of interpolation weight landing on filled
    // cells; the cycle sample is divided by that fraction so empty cells don't
    // drain volume. Only consulted in grid mode when !wtAbsoluteBlend.
    Terrain wtGridOccupancy;
    bool wtGridHasEmptyCells = false; // true if any cell is empty (mask worth applying)
    std::vector<std::vector<float>> wtScatterFrameSamples; // [frame][sample]
    std::vector<std::vector<float>> wtScatterFramePositions; // [frame][dim]

    // ---- Granular layer (parallel to the cycle layer) ----
    //
    // GranularFrame cells in the wavetable are NOT baked into the cycle
    // terrain (the cells store zeros there) - instead the synth runs a
    // per-voice 4-voice OLA granular stream for each granular frame and
    // mixes it in by the same morph weight the cycle layer would use.
    //
    // For grid mode: position is the frame's grid coord normalized to
    // [0,1] per dimension (so (gx / max(1, dims[d]-1))). The per-block
    // weight is the N-linear interp weight of the current Position into
    // this grid cell.
    //
    // For scatter mode: position is the frame's authored scatter position
    // (already in [0,1]). The per-block weight is the Wendland RBF weight
    // divided by the total RBF weight (same normalization the cycle
    // layer uses).
    struct GranularLayerEntry {
        // Source PCM, owned. Voice readers index into this directly via
        // the frame index; mid-session script reload of a __wavetable2__
        // synth would reset the table, but reloadIfScriptChanged only
        // handles __layered__ reloads, so for wavetable2 sources this
        // vector is stable for the processor's lifetime.
        std::vector<float> source;
        double             sourceSampleRate = 0.0;
        int                grainLength      = 4800;
        // Start sample of the freeze WINDOW (band) within source. -1 ==
        // auto-centre (legacy). Mirrors GranularFrame::windowStart so the synth
        // freezes the exact band the editor/audition show.
        int                windowStart      = -1;
        // Width (samples) of the freeze window; -1 == auto (== grainLength).
        // Decoupled from grainLength. Mirrors GranularFrame::windowLen.
        int                windowLen        = -1;
        float              embeddedPitchHz  = 440.0f;
        // Freeze-mode for held notes. Mirrors GranularFrame::freezeMode
        // (0=CrossfadeLoop, 1=AsyncGranular, ...). The synth voice
        // branches on this so "what you audition = what you get": the
        // capture/freeze audition plays CrossfadeLoop, so the synth
        // must too. Stored as int to avoid pulling granular_frame.h's
        // enum into this header.
        int                freezeMode       = 0;   // 0 = CrossfadeLoop
        // Overlapping-grain count for the two grain-cloud modes (Async /
        // Pitch-sync). Mirrors GranularFrame::grainCount; [2,16], 4 = the
        // historical hardcoded value (byte-identical at 4). Ignored by
        // CrossfadeLoop / SpectralFreeze.
        int                grainCount       = 4;
        // Requested SpectralFreeze FFT size (power-of-two). Mirrors
        // GranularFrame::fftSize; 0 == auto (largest pow2 <= min(window,2048)).
        // Ignored by the non-spectral modes.
        int                fftSize          = 0;
        // Seam crossfade length in samples, used by CrossfadeLoop.
        // Clamped per-sample to [0, grainLength/2] by the reader.
        int                crossfadeSamples = 2400;
        // Per-frame output gain (mirrors IWavetableFrame::gain). The cycle
        // layer applies a frame's gain inside render(); the granular layer
        // reads source PCM directly (bypassing render()), so the voice
        // multiplies the rendered grain by this so the editor's Gain knob -
        // and the capture dialog's Gain control - actually changes the
        // loudness of granular frames. 1.0 = unity.
        float              gain             = 1.0f;
        // Bucket C element warp (amplitude-domain waveshaping). Pre-filtered
        // enabled amplitude ops from GranularFrame::warpChain, captured at
        // rebuild. Applied to this frame's per-sample grain-stream output
        // BEFORE the morph weight / gain, so the live granular audio carries
        // the same transfer the editor bakes into the representative cycle
        // (GranularFrame::renderRaw). Empty = no warp (zero per-sample cost).
        // Granular has no periodic phase axis, so only amplitude ops apply
        // (the editor restricts the picker accordingly); phase ops, if a
        // hand-edited file carried any, were dropped by warpAmpOps().
        std::vector<WarpOp> warpAmpOps;
        // Position in the wavetable's N-D Position space, normalized
        // [0,1] per dim. For grid frames this is the grid-cell coord
        // mapped to [0,1]; for scatter frames it's the authored coord.
        std::vector<float> position;
    };
    std::vector<GranularLayerEntry> wtGranularFrames;

    // Per-block granular weights, sized to wtGranularFrames.size(). Filled
    // at the top of each processBlock from the current Position, then read
    // per-sample. Kept as a member so we don't realloc every block.
    std::vector<float> granWeights;

    // Recompute granWeights from the current Position params. Called once
    // per block.
    void updateGranularWeights();

    // ---- Inharmonic stack layer (Milestone 9) ----
    //
    // Like the granular layer, an inharmonic frame is NOT baked into the cycle
    // terrain - it bakes a zero cycle and registers a side-table entry here that
    // a per-voice oscillator bank reads live. The voice plays one sine per
    // partial at noteHz * ratio, sums amp*sin, scales by normGain (so it is as
    // loud as the editor's normalised thumbnail), applies the amplitude-domain
    // element warp, then the per-frame gain, and finally the per-block morph
    // weight - exactly mirroring how the granular layer is mixed. Mirrors
    // InharmonicFrame's fields without pulling inharmonic_frame.h into this
    // header (same convention GranularLayerEntry follows for granular_frame.h).
    struct InharmonicLayerEntry {
        struct Partial { float ratio = 1.0f; float amp = 1.0f; float phase = 0.0f; };
        std::vector<Partial> partials;
        // Per-frame output gain (mirrors IWavetableFrame::gain). The cycle layer
        // applies gain inside render(); the additive voice bypasses render(), so
        // the voice multiplies its summed output by this.
        float               gain     = 1.0f;
        // Peak-normalisation factor = InharmonicFrame::normGainFor(partials),
        // captured at rebuild. The live bank has no normalisation of its own, so
        // multiplying by this makes a placed frame as loud as its editor preview.
        float               normGain = 1.0f;
        // Bucket C amplitude-domain element warp (enabled ops only), applied to
        // the bank's per-sample output before gain/weight, matching renderRaw.
        std::vector<WarpOp> warpAmpOps;
        // Position in the wavetable's N-D Position space, normalised [0,1] per
        // dim (grid-cell coord mapped to [0,1], or the authored scatter coord).
        std::vector<float>  position;
    };
    std::vector<InharmonicLayerEntry> wtInharmonicFrames;

    // Per-block inharmonic morph weights, sized to wtInharmonicFrames.size().
    std::vector<float> inhWeights;

    // Recompute inhWeights from the current Position params. Called once/block.
    void updateInharmonicWeights();

    // Compute per-inharmonic-frame morph weights for an arbitrary Position into
    // `out`. The audition path calls it with a per-voice override Position.
    void computeInharmonicWeights(const std::vector<float>& pos,
                                  std::vector<float>& out);

    // Build the geometric-axis-indexed scatter query point from the live
    // Position params. Position params exist only for *traversable* axes
    // (wtEffectiveAxes), numbered contiguously; every non-traversable axis
    // stays at 0.5 (the dot-plane center). So a lone dot under "distance
    // fades volume" exposes a single radial-proximity knob ("Position")
    // while its other coordinates pin to the dot's center, and a multi-dot
    // scatter exposes one knob per dimension as before. Used by both the
    // block-start cycle blend and updateGranularWeights so they agree.
    std::vector<float> scatterQueryPosition();

    // Compute per-granular-frame morph weights for an arbitrary Position
    // vector into `out` (resized to wtGranularFrames.size()). updateGranular-
    // Weights() is just this called with the live Position params; audition
    // voices call it with their own per-voice override Position so a frame's
    // Play button in the wavetable editor auditions THAT frame regardless of
    // where the live Position knob sits.
    void computeGranularWeights(const std::vector<float>& pos,
                                std::vector<float>& out);

    // Shared morph-weight kernel for the non-cycle side layers (granular and
    // inharmonic). Given each side-table entry's normalised Position
    // (entryPositions[i]) and a query Position `pos`, fills `out[i]` with the
    // same blend weight the cycle layer would give that location: scatter uses
    // the Shepard / Wendland RBF normalised against ALL scatter frames; grid
    // uses the N-linear hat-function product. computeGranularWeights and
    // computeInharmonicWeights are thin wrappers that gather their entries'
    // positions and call this, so the two layers morph identically.
    void computeSideTableWeights(const std::vector<std::vector<float>>& entryPositions,
                                 const std::vector<float>& pos,
                                 std::vector<float>& out);

    // Allocate (stealing the quietest if all busy) and start a voice for a
    // note-on. Returns the voice index, or -1 if none could be allocated.
    // Shared by the MIDI note-on path and the UI audition drain so both go
    // through identical envelope / velocity / pitch-bend seeding. Clears any
    // stale audition override on the reused voice. velocity is 0..127.
    int  startVoice(int noteNumber, int channel, int velocity);
    // Release every active voice matching noteNumber on `channel` (honouring
    // the sustain pedal). Shared by the MIDI note-off path and the audition
    // drain's note-off.
    void releaseNote(int noteNumber, int channel);

    // Shared AHDSR amplitude envelope. The baked curve tables live on the
    // processor (one set per node, sampled by every voice); each Voice owns
    // a lightweight AHDSREnvelopeRuntime for playback. `effectiveEnv` is a
    // per-block copy of node.ahdsrEnvelope with the legacy "Vel Sens" param
    // folded into velocitySensitivity for backward compatibility.
    AHDSRCurveTables envTables;
    AHDSREnvelope    effectiveEnv;
    void rebuildEnvCurves();   // refreshes effectiveEnv + bakes envTables

    // Voices
    struct Voice {
        // "Active" (slot in use) is derived from env.isActive().
        int noteNumber = -1;
        int midiChannel = 1;       // 1..16, used for per-channel bend / mod wheel
        float baseFrequency = 440.0f; // frequency before bend, set at note-on
        float frequency = 440.0f;  // effective frequency (base * bend), used by render
        float phase = 0.0f;
        double startBeat = 0;
        // Sustain pedal: true if this voice received a note-off while CC64
        // was down, so release is deferred until the pedal comes back up.
        bool sustainHeld = false;

        // Shared per-voice amplitude envelope runtime (Attack, Hold, Decay,
        // Sustain, Release). Driven by the processor's effectiveEnv +
        // envTables. Velocity is applied inside the runtime via the
        // envelope's velocitySensitivity, so the render loop must NOT apply
        // a separate velocity multiply.
        AHDSREnvelopeRuntime env;

        // Per-note (polyphonic) aftertouch value 0..1. Set by
        // poly-pressure MIDI events; layered on top of the per-channel
        // aftertouch in the render loop. MPE-style controllers route
        // independent pressure per voice via this field.
        float polyAftertouch = 0.0f;

        // Additive-bank mode per-partial phases. Allocated lazily on the
        // first note-on that enters AdditiveBank mode so the Voice array
        // doesn't pay the ~256 byte / voice cost when this mode is unused.
        std::vector<float> partialPhases;

        // Per-granular-frame playback state. One entry per
        // GranularLayerEntry in TerrainSynthProcessor::wtGranularFrames.
        // Allocated lazily on note-on once the granular table is known.
        // GrainFreezeVoice is the SHARED freeze-mode reader (granular_freeze.h)
        // that the capture/freeze audition engine also uses, so every freeze
        // mode (CrossfadeLoop, AsyncGranular, PitchSyncGrains, SpectralFreeze)
        // sounds identical whether auditioned in the dialog or played as a
        // held note. The voice carries all per-mode playback state internally.
        struct GranStream {
            GrainFreezeVoice voice;
        };
        std::vector<GranStream> granStreams;

        // Per-inharmonic-frame oscillator-bank state. One entry per
        // InharmonicLayerEntry in wtInharmonicFrames; each holds one running
        // phase accumulator per partial. Cleared on every note-on (startVoice)
        // so phases restart from the partials' authored initial phases - tonal
        // partials would click otherwise. Lazily (re)sized on first use in the
        // voice loop, which also seeds each phase from the entry's partial.
        struct InhStream { std::vector<float> phase; };
        std::vector<InhStream> inhStreams;
        // Per-voice inharmonic morph weights for wavetable-editor audition
        // voices (mirrors auditionWeights for the granular layer).
        std::vector<float> auditionInhWeights;

        // Wavetable-editor audition override. When a Play button in the
        // wavetable editor triggers this voice, hasAuditionPos is set and
        // auditionPos holds the edited frame's normalized Position. The
        // granular layer then uses auditionWeights (computed per block from
        // auditionPos) instead of the synth-wide granWeights, so the voice
        // plays the frame being edited rather than whatever the live Position
        // knob selects. Plain MIDI / timeline notes leave this false and use
        // the shared granWeights. Reset on every voice (re)allocation.
        bool               hasAuditionPos = false;
        std::vector<float> auditionPos;
        std::vector<float> auditionWeights;

        // Direct unplaced-frame audition. When the wavetable editor's Play
        // button auditions a granular library frame that isn't placed into
        // the grid/scatter, the note-on carries the frame data here. The
        // voice then renders ONLY this frame (full weight, its own playhead),
        // bypassing the cycle terrain and the placed-frame morph entirely, so
        // a freshly-captured library-only frame is audible without first
        // dropping it into a cell. Null on every ordinary note. Reset on
        // voice (re)allocation alongside hasAuditionPos.
        std::shared_ptr<Node::AuditionGranularFrame> auditionFrame;
        GranStream                                    auditionFrameStream;

        // Same direct-audition mechanism for an unplaced inharmonic stack: the
        // inharmonic editor's Play button ships the frame here and the voice
        // renders ONLY its oscillator bank, bypassing the cycle terrain and the
        // placed-frame morph. Null on every ordinary note. Reset on voice
        // (re)allocation alongside auditionFrame.
        std::shared_ptr<Node::AuditionInharmonicFrame> auditionInhFrame;
        InhStream                                       auditionInhFrameStream;

        // Direct single-cycle audition (the layered-waveform editor's Play
        // button, generalisable to every frame editor). When set, the voice
        // reads ONLY this cycle as a wavetable oscillator at the played pitch
        // (using the same v.phase accumulator the placed-cycle path uses),
        // bypassing the cycle terrain + granular + inharmonic layers, so an
        // unplaced edited frame is audible exactly as the editor previews it.
        // Null on every ordinary note. Reset on voice (re)allocation alongside
        // auditionFrame / auditionInhFrame.
        std::shared_ptr<Node::AuditionCycleFrame> auditionCycleFrame;

        // De-click crossfade for live cycle swaps. When the editor re-ships a
        // freshly rendered cycle while the held Preview note sustains (dragging a
        // morph slider), the synth swaps auditionCycleFrame in place. Reading a
        // new table mid-phase steps the output -> a click. To match the smooth
        // per-sample signal path, we keep the previous cycle and equal-linearly
        // crossfade from it to the new one over a few ms: auditionCyclePrev holds
        // the cycle we're fading FROM, auditionCycleFade ramps 0->1 (1 = fully on
        // the current cycle). Reset alongside auditionCycleFrame.
        std::shared_ptr<Node::AuditionCycleFrame> auditionCyclePrev;
        float                                     auditionCycleFade = 1.0f;
    };
    static constexpr int MAX_VOICES = 16;
    Voice voices[MAX_VOICES];

    // Reusable per-block scratch for audition voices diverted to the
    // AudioEngine audition-monitor bus (editor "Play" on an unrouted synth
    // node - see Node::reachesOutput). Sized to the block in processBlock;
    // never read across blocks. Avoids a per-block heap allocation.
    std::vector<float> auditionScratch;

    // Snapshot of the incoming control-signal channels (buffer channels 2+:
    // the "Sig X/Y/.." coordinate drivers and the "Pressure" signal pin),
    // captured at the top of processBlock BEFORE buf.clear() wipes them. The
    // buffer is the synth's render target, so clearing it to start the voice
    // mix also destroys the incoming signal; without this snapshot the
    // per-sample Sig-coordinate and pressure readers would see only zeros
    // (coordinate pinned to 0, pressure override never engaging). Channel
    // c here mirrors buf channel c+2. Sized per block; reused to avoid a
    // per-block heap allocation on the audio thread.
    juce::AudioBuffer<float> controlInBuf;

    // Per-channel pitch bend factor (1.0 = no bend, 2^(semis/12) otherwise).
    // Default bend range is +/-2 semitones - configurable per-synth later.
    float pitchBendFactor[16] = {1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1};
    static constexpr float kPitchBendRangeSemis = 2.0f;

    // Per-channel mod wheel (CC#1) value, normalized 0..1. Drives a default
    // fixed-rate vibrato on the voice frequency when > 0.
    float modWheel[16] = {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
    float vibratoPhase = 0.0f;
    static constexpr float kVibratoRateHz = 6.0f;
    static constexpr float kVibratoMaxSemis = 0.4f; // +/-0.4 semis at full mod

    // Per-channel sustain pedal (CC#64) state. While true, note-offs are
    // captured as sustainHeld instead of immediately releasing.
    bool sustainPedal[16] = {false,false,false,false,false,false,false,false,
                              false,false,false,false,false,false,false,false};

    // Per-channel aftertouch (channel pressure, CC-like value 0..1). Set
    // by isChannelPressure() MIDI events; consumed in the render loop
    // as a volume swell multiplier scaled by node.aftertouchSensitivity.
    // The "Pressure" Signal input pin on the synth, when wired,
    // overrides this with the wired signal's current sample value
    // instead (lets users drive the swell from any signal source -
    // LFO, XY pad, automation, another voice's amplitude, etc.)
    float channelAftertouch[16] = {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
    // Set per-block from the "Pressure" Signal input pin when it's
    // wired. Negative means "unwired - fall back to MIDI value".
    float aftertouchOverride = -1.0f;

    // Internal LFOs for modulation
    struct LFO {
        float frequency = 1.0f;  // Hz
        float phase = 0.0f;
        float advance(float sr) {
            float v = std::sin(phase * 2.0f * 3.14159265f);
            phase += frequency / sr;
            if (phase > 1.0f) phase -= 1.0f;
            return v;
        }
    };
    LFO lfo1, lfo2;

    // Graintable parameters
    float grainSize = 0.0f;       // in seconds, 0 = off (raw sample), >0 = crossfaded grains
    bool grainFreeze = false;      // freeze at current position
    float freezePosition = 0.0f;   // captured position when freeze was activated

    std::vector<float> lastPosition; // for UI visualization

    // Additive-bank cache: harmonic magnitudes and phases extracted from the
    // current 1D wavetable cycle (or the current scatter-blended cycle).
    // Computed once per block (or on cycle change) so the per-sample loop
    // is just N sine-table reads + an accumulate.
    struct PartialBank {
        std::vector<float> magnitude; // size = kAdditiveBankMaxPartials
        std::vector<float> phase;     // size = kAdditiveBankMaxPartials
        bool valid = false;
        // Fingerprint of the cycle this was computed from, so we don't
        // recompute on every block when the cycle is static.
        size_t cycleHash = 0;
    };
    PartialBank partialBank;
    // Refresh partialBank from the current 1D terrain cycle (or
    // wtScatterFrameSamples blended at the current Position when in
    // scatter mode).
    void refreshPartialBank();

    float getParam(int idx, float def) const;
};

} // namespace SoundShop
